<div class="d-flex flex-wrap flex-row align-items-center" id="topBar">
	<div class="module btn" id="status">
		<div
			class="d-inline-flex flex-wrap align-items-center slide-right-toggle"
			aria-expanded="false">
			<h4 class="p-2 d-inline">Status :</h4>
			<img src="/img/yellow_light.png" id="StatusIcon" class="p-1 d-inline effect-toggle"
				data-target="ServerActions" style="width: 50px; height: 50px;">
		</div>
	</div>

	<div id="ServerActions" class="module-slider bg-light" role="group" data-effect="slide" data-duration="800" style="display: none;">
		<button type="button" class="btn btn-secondary">Start</button>
		<button type="button" class="btn btn-secondary">Stop</button>
		<button type="button" class="btn btn-secondary">Restart</button>
	</div>
</div>

<div class="module" id="listplayer">
	<div class="d-flex container-fluid">
		<div class="table-title">Online Players</div>
		<div class="ml-auto">
			<span id="numplayers">N/A</span> (<span id="maxplayers">N/A)</span>)
		</div>
	</div>
	<div class="container-fluid bg-light scroll-y">
		<ul class="list-group" id="players">
		</ul>
	</div>
</div>

<script src="js/server-status.js"></script>